p = 'app/services/optimizer_service.py'
s = open(p, encoding='utf-8').read()

# Add import for the deterministic fallback parser.
old_import = 'from ..llm.interpreter import NoteInterpreter, build_default_interpreter'
new_import = (
    'from ..llm.fallback_parser import fallback_parse\n'
    'from ..llm.interpreter import NoteInterpreter, build_default_interpreter'
)
assert old_import in s, 'interpreter import marker not found'
s = s.replace(old_import, new_import)

# Insert the fallback step right after raw_entries assignment.
old_anchor = (
    '        # 1. LLM interpretation (with deterministic validator inside).\n'
    '        raw_entries = self._interpreter.interpret(request.operator_notes)\n'
    '\n'
    '        # 2. Normalize against the request -- this guarantees one safe entry\n'
    '        #    per note, in order, with the correct structured_adjustment shape.\n'
    '        directives = normalize_entries('
)
new_block = (
    '        # 1. LLM interpretation (with deterministic validator inside).\n'
    '        raw_entries = self._interpreter.interpret(request.operator_notes)\n'
    '\n'
    '        # 1b. Deterministic fallback: when the LLM misclassifies a note as\n'
    '        #     no_op or returns empty hours, the fallback parser re-reads\n'
    '        #     the note text and emits a safe directive. The fallback is\n'
    '        #     generic -- it does not consult any sample-specific phrasing.\n'
    '        raw_entries = _apply_fallback(\n'
    '            raw_entries,\n'
    '            request.operator_notes,\n'
    '            capacity_kwh=request.battery.capacity_kwh,\n'
    '        )\n'
    '\n'
    '        # 2. Normalize against the request -- this guarantees one safe entry\n'
    '        #    per note, in order, with the correct structured_adjustment shape.\n'
    '        directives = normalize_entries('
)
assert old_anchor in s, 'pipeline anchor marker not found'
s = s.replace(old_anchor, new_block)

helper = (
    '\n\ndef _apply_fallback(\n'
    '    raw_entries: list,\n'
    '    operator_notes: list,\n'
    '    *,\n'
    '    capacity_kwh: float | None = None,\n'
    ') -> list:\n'
    '    """Recover from LLM misclassifications using the deterministic fallback.\n'
    '\n'
    '    Three recovery rules:\n'
    '\n'
    '      R1. LLM says no_op but the fallback detects a real directive -- use\n'
    '          the fallback result. Catches the "downgrade to no_op" failure\n'
    '          mode documented in fallback_parser.py.\n'
    '      R2. LLM says applies=true with empty hours while the fallback has\n'
    '          non-empty hours -- use the fallback hours. Catches the\n'
    '          "zeroed constraint" failure mode.\n'
    '      R3. LLM emits factor=0.5 default for solar_reduction but the note\n'
    '          text contains an explicit percentage -- use the fallback\n'
    '          factor.\n'
    '\n'
    '    Each rule fires only when the fallback is strictly more informative\n'
    '    than the LLM output, so the fallback never silently downgrades.\n'
    '    """\n'
    '    if not operator_notes:\n'
    '        return raw_entries\n'
    '    by_idx = {}\n'
    '    for e in raw_entries or []:\n'
    '        if isinstance(e, dict):\n'
    '            try:\n'
    '                ni = int(e.get("note_index", -1))\n'
    '            except (TypeError, ValueError):\n'
    '                continue\n'
    '            by_idx.setdefault(ni, e)\n'
    '    for idx, note in enumerate(operator_notes):\n'
    '        if not isinstance(note, str):\n'
    '            continue\n'
    '        fb = fallback_parse(note, idx, capacity_kwh=capacity_kwh)\n'
    '        llm = by_idx.get(idx)\n'
    '        if not isinstance(llm, dict):\n'
    '            by_idx[idx] = fb\n'
    '            continue\n'
    '        llm_type = llm.get("directive_type")\n'
    '        fb_type = fb.get("directive_type")\n'
    '        llm_applies = bool(llm.get("applies", False))\n'
    '        fb_applies = bool(fb.get("applies", False))\n'
    '\n'
    '        # R1: LLM no_op but fallback found a directive.\n'
    '        if not llm_applies and fb_applies:\n'
    '            by_idx[idx] = fb\n'
    '            continue\n'
    '\n'
    '        if not fb_applies:\n'
    '            continue\n'
    '\n'
    '        llm_adj = llm.get("structured_adjustment") or {}\n'
    '        fb_adj = fb.get("structured_adjustment") or {}\n'
    '\n'
    '        # R2: LLM hours empty, fallback hours populated.\n'
    '        llm_hours = llm_adj.get("hours") or []\n'
    '        fb_hours = fb_adj.get("hours") or []\n'
    '        if isinstance(llm_hours, list) and isinstance(fb_hours, list):\n'
    '            if not llm_hours and fb_hours:\n'
    '                llm_adj = {**llm_adj, "hours": fb_hours}\n'
    '                llm["structured_adjustment"] = llm_adj\n'
    '                by_idx[idx] = llm\n'
    '                continue\n'
    '\n'
    '        # R3: solar_reduction factor sanity.\n'
    '        if (\n'
    '            llm_type == "solar_reduction"\n'
    '            and fb_type == "solar_reduction"\n'
    '            and fb_adj.get("factor") is not None\n'
    '            and fb_adj.get("factor") != 0.5\n'
    '            and llm_adj.get("factor") in (None, 0.5)\n'
    '        ):\n'
    '            llm_adj = {**llm_adj, "factor": fb_adj["factor"]}\n'
    '            llm["structured_adjustment"] = llm_adj\n'
    '            by_idx[idx] = llm\n'
    '\n'
    '    return [by_idx[i] for i in sorted(by_idx)]\n'
)
s = s.rstrip() + helper + '\n'

open(p, 'w', encoding='utf-8').write(s)
print('OK: fallback wired into optimizer_service.')
